import os
import random

names = [
    'Maria',
    'Nushi',
    'Mohammed',
    'Jose',
    'Muhammad',
    'Mohamed',
    'Wei',
    'Mohammad',
    'Ahmed',
    'Yan',
    'Ali',
    'John',
    'David',
    'Li',
    'Abdul',
    'Ana',
    'Ying',
    'Michael',
    'Juan',
    'Anna',
    'Mary',
    'Jean',
    'Robert',
    'Daniel',
    'Luis',
    'Carlos',
    'James',
    'Antonio',
    'Joseph',
    'Hui',
    'Elena',
    'Francisco',
    'Hong',
    'Marie',
    'Min',
    'Lei',
    'Yu',
    'Ibrahim',
    'Peter',
    'Fatima',
    'Aleksandr',
    'Richard',
    'Xin',
    'Bin',
    'Paul',
    'Ping',
    'Lin',
    'Olga',
    'Sri',
    'Pedro',
    'William',
    'Rosa',
    'Thomas',
    'Jorge',
    'Yong',
    'Elizabeth',
    'Sergey',
    'Ram',
    'Patricia',
    'Hassan',
    'Anita',
    'Manuel',
    'Victor',
    'Sandra',
    'Ming',
    'Siti',
    'Miguel',
    'Emmanuel',
    'Samuel',
    'Ling',
    'Charles',
    'Sarah',
    'Mario',
    'Joao',
    'Tatyana',
    'Mark',
    'Rita',
    'Martin',
    'Svetlana',
    'Patrick',
    'Natalya',
    'Qing',
    'Ahmad',
    'Martha',
    'Andrey',
    'Sunita',
    'Andrea',
    'Christine',
    'Irina',
    'Laura',
    'Linda',
    'Marina',
    'Carmen',
    'Ghulam',
    'Vladimir',
    'Barbara',
    'Angela',
    'George',
    'Roberto',
    'Peng',
    'Ivan',
    'Alexander',
    'Ekaterina',
    'Qiang',
    'Yun',
    'Jesus',
    'Susan',
    'Sara',
    'Noor',
    'Mariam',
    'Dmitriy',
    'Eric',
    'Zahra',
    'Fatma',
    'Fernando',
    'Esther',
    'Jin',
    'Diana',
    'Mahmoud',
    'Chao',
    'Rong',
    'Santosh',
    'Nancy',
    'Musa',
    'Anh',
    'Omar',
    'Jennifer',
    'Gang',
    'Yue',
    'Claudia',
    'Maryam',
    'Gloria',
    'Ruth',
    'Teresa',
    'Sanjay',
    'Na',
    'Nur',
    'Kyaw',
    'Francis',
    'Amina',
    'Denis',
    'Stephen',
    'Sunil',
    'Gabriel',
    'Andrew',
    'Eduardo',
    'Abdullah',
    'Grace',
    'Anastasiya',
    'Mei',
    'Rafael',
    'Ricardo',
    'Christian',
    'Aleksey',
    'Steven',
    'Gita',
    'Frank',
    'Jianhua',
    'Mo',
    'Karen',
    'Masmaat',
    'Brian',
    'Christopher',
    'Xiaoyan',
    'Rajesh',
    'Mustafa',
    'Eva',
    'Bibi',
    'Monica',
    'Oscar',
    'Andre',
    'Catherine',
    'Kai',
    'Ramesh',
    'Liping',
    'Sonia',
    'Anthony',
    'Mina',
    'Manoj',
    'Ashok',
    'Rose',
    'Alberto',
    'Ning',
    'Rekha',
    'Chen',
    'Lan',
    'Aung',
    'Alex',
    'Suresh',
    'Anil',
    'Fatemeh',
    'Julio',
    'Zhen',
    'Simon',
    'Paulo',
    'Juana',
    'Irene',
    'Adam',
    'Kevin',
    'Vijay',
    'Syed',
    'Mehmet',
    'Angel',
    'Edward',
    'Julia',
    'Victoria',
    'Ronald',
    'Cheng',
    'Lakshmi',
    'Francisca',
    'Veronica',
    'Roman',
    'Ismail',
    'Margaret',
    'Luz',
    'Anne',
    'Silvia',
    'Kamal',
    'Raju',
    'Sergio',
    'Walter',
    'Lisa',
    'Marta',
    'Nadezhda',
    'Marco',
    'Albert',
    'Alice',
    'Asha',
    'Xiang',
    'Isabel',
    'Zainab',
    'Michelle',
    'Long',
    'Michel',
    'Pierre',
    'Saleh',
    'Haiyan',
    'Felix',
    'Salma',
    'Hector',
    'Manju',
    'Jan',
    'Roger',
    'Joyce',
    'Margarita',
    'Joel',
    'Jessica',
    'Lucia',
    'Pavel',
    'Hai',
    'Nadia',
    'Mariya',
    'Jianping',
    'Jacqueline',
    'Halima',
    'Nan',
    'Rama',
    'Benjamin',
    'Rebecca',
    'Julie',
    'Vera',
    'Vinod',
    'Kun',
    'Khalid',
    'Ramon',
    'Janet',
    'Sharon',
    'Suman',
    'Jane',
    'Lihua',
    'Shanti',
    'Abubakar',
    'Aisha',
    'Zaw',
    'Jonathan',
    'Paula',
    'Bruno',
    'Monika',
    'Maksim',
    'Mamadou',
    'Judith',
    'Kenneth',
    'Mostafa',
    'Chris',
    'Helen',
    'Nikolay',
    'Rina',
    'Zhiqiang',
    'Marcos',
    'Mária',
    'Norma',
    'Anton',
    'Raul',
    'Cristina',
    'Xiaohong',
    'Henry',
    'Wai',
    'Antonia',
    'Betty',
    'Alejandro',
    'Nelson',
    'Igor',
    'Evgeniy',
    'Adriana',
    'Amir',
    'Pablo',
    'Raj',
    'Regina',
    'Rajendra',
    'Brenda',
    'Linh',
    'Sani',
    'Hussein',
    'Gul',
    'Mikhail',
    'Jaime',
    'Nicole',
    'Sima',
    'Giuseppe',
    'Dinesh',
    'Tatiana',
    'Bernard',
    'Gary',
    'Lijun',
    'Sita',
    'Javier',
    'Shan',
    'Hasan',
    'Yuliya',
    'Ni',
    'Moses',
    'Agnes',
    'Cesar',
    'Xiaoli',
    'Usha',
    'Alfredo',
    'Meng',
    'Jianguo',
    'Kiran',
    'Dennis',
    'Khaled',
    'Carol',
    'Rani',
    'Yusuf',
    'Xiaoping',
    'Ha',
    'Rakesh',
    'Isaac',
    'Luiz',
    'Josephine',
    'Krishna',
    'Mohamad',
    'Raymond',
    'Erika',
    'Blanca',
    'Jianjun',
    'Deborah',
    'Amanda',
    'Natalia',
    'Gladys',
    'Florence',
    'Asma',
    'Usman',
    'Donald',
    'Lijuan',
    'Zhi',
    'Abdullahi',
    'Stephanie',
    'Tingting',
    'Saeed',
    'Edgar',
    'Maya',
    'Han',
    'Mahdi',
    'Khadija',
    'Valentina',
    'Ruben',
    'Tuan',
    'Thanh',
    'Jason',
    'Ei',
    'Doris',
    'Fatoumata',
    'Darya',
    'Rene',
    'Cecilia',
    'Umar',
    'Cynthia',
    'Gustavo',
    'Kim',
    'Lucas',
    'Zin',
    'Xuan',
    'Abdo',
    'Moussa',
    'Amit',
    'Mona',
    'Xiaoling',
    'Dilip',
    'Caroline',
    'An',
    'Tun',
    'Muhammed',
    'Claude',
    'Elisabeth',
    'Yuanyuan',
    'Beatrice',
    'Edwin',
    'Xiaodong',
    'Hung',
    'Kristina',
    'Scott',
    'Christina',
    'Ajay',
    'Alina',
    'Denise',
    'Matthew',
    'Vladymyr',
    'Daniela',
    'Pushpa',
    'Joan',
    'Leonardo',
    'Aleksandra',
    'Ravi',
    'Virginia',
    'Hamid',
    'Alain',
    'António',
    'Lyubov',
    'Xiaoming',
    'Alicia',
    'Mohan',
    'Hans',
    'Xing',
    'Ann',
    'Laoshi',
    'Santos',
    'Di',
    'Said',
    'Haji',
    'Nicolas',
    'Felipe',
    'Amal',
    'Bekele',
    'Donna',
    'Dina',
    'Hugo',
    'Yolanda',
    'Laxmi',
    'Munni',
    'Maryia',
    'Beatriz',
    'Urmila',
    'Mukesh',
    'Brigitte',
    'Radha',
    'Evelyn',
    'Emma',
    'Kenji',
    'Galina',
    'Diego',
    'Viktor',
    'Arun',
    'Alexandra',
    'Alfred',
    'Chun',
    'Huan',
    'Nykolai',
    'Louis',
    'Armando',
    'Sunday',
    'Vincent',
    'Edith',
    'Jingjing',
    'Samira',
    'Zhiyong',
    'Alan',
    'Hiroshi',
    'Gabriela',
    'Savitri',
    'Rachel',
    'Adrian',
    'Mira',
    'Shankar',
    'Carla',
    'Miriam',
    'Gopal',
    'Yanping',
    'Lyudmila',
    'Lalita',
    'Magdalena',
    'Xiaohua',
    'Anwar',
    'Sushila',
    'Jianming',
    'Amy',
    'Mercy',
    'Timothy',
    'Irma',
]

countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Côte d\'Ivoire',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Democratic Republic of the Congo',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
]

hobbies = [
    'hiking',
    'backpacking',
    'camping',
    'pickleball',
    'fishing',
    'archery',
    'canoeing',
    'kayaking',
    'running',
    'geocaching',
    'volleyball',
    'gardening',
    'bird watching',
    'beekeeping',
    'painting',
    'skateboarding',
    'antiquing',
    'coin collecting',
    'collecting seashells',
    'meditation',
    'yoga',
    'cooking',
    'baking',
    'swimming',
    'brewing beer',
    'sewing',
    'origami',
    'photography',
    'scrapbooking',
    'calligraphy',
    'quitling',
    'crocheting',
    'knitting',
    'pottery',
    'wood carving',
    'DIY projects',
    'playing with LEGO',
    'trivia',
    'video games',
    'board games',
    'card games',
    'chess',
    'puzzles',
    'table tennis',
    'billiards',
    'genealogy',
    'language learning',
    'journaling',
    'writing',
    'reading',
    'playing guitar',
    'thrifting',
    'dancing',
    'tinkering',
    'traveling',
    'scuba diving',
    'mountain biking',
    'coffee roasting',
    'hunting',
]

tenses = [
    {
        "name": 'present simple',
        "example": 'I study every day.'
    },
    {
        "name": 'present continuous',
        "example": 'I\'m studying English now.'
    },
    {
        "name": 'present perfect',
        "example": 'I\'ve studied for four years.'
    },    
    {
        "name": 'past simple',
        "example": 'I studied yesterday.'
    },
    {
        "name": 'past continuous',
        "example": 'I was studying a few hours ago.'
    },
    {
        "name": 'future',
        "example": 'I\'ll study tomorrow.'
    },
]

while(True):
    os.system('clear')
    name = random.choice(names)
    country = random.choice(countries)
    hobby = random.choice(hobbies)
    random_tense = random.choice(tenses)
    for tense in tenses:
        print('{0: <20}'.format(f'{tense["name"]}') + '=>\t\t' + f'{tense["example"]}')
    print('')
    print(f'PROMPT: {name} is from {country} and enjoys {hobby}.')
    print(f'EXERCISE: Please create a sentence about {name} using the {random_tense["name"]} verb tense.\n')
    input('')